name: release-notes

on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  RELEASE_DIR: .cr-release-packages

permissions:
  contents: write # Allow to create a release.

jobs:
  release:
    name: Create Release notes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create release notes
        uses: docker://decathlon/release-notes-generator-action:2.0.1
        env:
          GITHUB_TOKEN: ${GH_TOKEN}
          OUTPUT_FOLDER: ${RELEASE_DIR}
          USE_MILESTONE_TITLE: "true"

